Added: Swipe module, Api connected to retrieve an array of movies
johnandblue/spotamovieFE pull request #2
Opened 2017-01-28 18:02 UTC by johnandblue

2017-01-29 21:33 UTC, arol requested changes

2017-01-29 21:33 UTC, arol commented on App/actions/actions.js
> +// export const addMovies = (movies) => ({
Unused code should be deleted.

2017-01-29 21:33 UTC, arol commented on App/reducers/reducers.js
> +    // case 'ADD_MOVIES':
The same as before. Unused code should be deleted.

2017-01-29 21:33 UTC, arol commented on App/reducers/reducers.js
> +// const user = (state = {}, action) => {
Same as above. Keep it clean, "saving it for later" is not a reason to keep this in here.

2017-01-29 21:33 UTC, arol commented on app/actions/actions_template.js
> +// import { CALL_API } from '../lib/api'
Same.

2017-01-29 21:33 UTC, arol commented on app/containers/AppContainer.js
> +const path = 'https://movied.herokuapp.com/popular';
Unused constant? This shouldn't be here. Try to put this on the actions or the middleware.

2017-01-30 08:57 UTC, johnandblue commented on App/actions/actions.js
> +// export const addMovies = (movies) => ({
@arol Changes made. Deleted unused code

2017-01-30 08:58 UTC, johnandblue commented on App/actions/actions.js
> +// export const addMovies = (movies) => ({
Changes made. Deleted unused code

2017-01-30 08:58 UTC, johnandblue commented on App/reducers/reducers.js
> +    // case 'ADD_MOVIES':
Changes made. Deleted unused code

2017-01-30 08:58 UTC, johnandblue commented on App/reducers/reducers.js
> +// const user = (state = {}, action) => {
Done.

2017-01-30 08:59 UTC, johnandblue commented on app/containers/AppContainer.js
> +const path = 'https://movied.herokuapp.com/popular';
Moved to a folder used for constants like Path for popular movies, or the path for the poster.

2017-01-30 08:59 UTC, johnandblue commented on app/actions/actions_template.js
> +// import { CALL_API } from '../lib/api'
Done

2017-01-30 09:03 UTC, arol commented
👍

2017-01-30 09:03 UTC, arol approved these changes

2017-01-30 09:04 UTC, merged