Connected login to actions and api, getting user as props
johnandblue/spotamovieFE pull request #4
Opened 2017-01-30 20:23 UTC by johnandblue

2017-01-31 11:58 UTC, arol requested changes
Please solve conflicts first

2017-01-31 16:47 UTC, arol commented
Conflicts are still not resolved. 😞

2017-01-31 16:58 UTC, johnandblue commented
@arol Conflicts resolved, ready to merge

2017-02-01 16:08 UTC, johnandblue commented
Waiting for approval to merge

2017-02-02 16:07 UTC, arol requested changes

2017-02-02 16:07 UTC, arol commented on app/components/Swiper/SwiperEL.js
> +  //
Unused code

2017-02-02 16:07 UTC, arol commented on app/components/Swiper/SwiperEL.js
> +            onPress={this.clicLike}
Does this function exist?

2017-02-02 16:34 UTC, johnandblue commented
@arol 
Unused code solved, 
SwiperEl is an outdated version, the new one is the branch that we are working actually

2017-02-02 16:34 UTC, arol approved these changes

2017-02-02 16:34 UTC, arol commented
All yours, then.

2017-02-02 16:35 UTC, merged